[achivement]
grasslands = "First Green"
forests = "Forester"
animals = "Animal Keeper"
civilize = "Monolith"
green-planet = "Green Planet"
melted-ice = "Melted Ice"
artificial-blue-sky = "Artificial Blue Sky"
desert-greening = "Desert Greening"
industrial-revolution = "Industrial Revolution"
inter-species-war = "Interspecies War"
pandemic = "Pandemic"
step-toward-ecumenopolis = "The First Step Toward Ecumenopolis"
magical-energy = "Magical Energy"
abundant-power = "Abundant Power"
exodus = "Exodus"
giant-mirror = "Giant Mirror"
low-carbon-dioxide = "Cannot Photosynthesize"
destroy-planet = "I don't need this"
dark-clouds = "Dark Clouds"
planet-sculpting = "Planet Sculpting"

[achivement.desc]
grasslands = "Spread grasslands to cover more than 10 tiles."
forests = "Spread forests to cover more than 50 tiles."
animals = "Introduce animal life onto the planet."
civilize = "Evolve animals into a civilization."
green-planet = "Reach a total biomass of 2000 Gt."
melted-ice = "Melt all the ice on an ice planet."
artificial-blue-sky = "Reach atmospheric pressure of 1 atm on a barren planet"
desert-greening = "Achieve 600 Gt of biomass on a desert planet."
industrial-revolution = "Advance a civilization to the Industrial Age."
inter-species-war = "Witness an interspecies war break out."
pandemic = "Have a plague infect more than 1000 cities." 
step-toward-ecumenopolis = "Cover more than 50% of the planet surface with cities and reach a population over 7,500,000."
magical-energy = "Supply Gift Energy to an Iron Age civilization."
abundant-power = "Generate 30,000 TW of power."
exodus = "Witness civilization's journey into space"
giant-mirror = "Build an orbital mirror."
low-carbon-dioxide = "Lower the atmospheric CO2 concentration below 0.00003 atm."
destroy-planet = "Make a thriving planet (500+ Gt biomass, 1000+ pop) barren within 3000 cycles."
dark-clouds = "Cover more than 80% of the planet with clouds"
planet-sculpting = "Sculpt the planet surface"
