[achivement]
grasslands = "まずは草を育てる"
forests = "森林管理人"
animals = "動物飼育"
civilize = "モノリス"
green-planet = "緑の惑星"
melted-ice = "溶けた氷"
desert-greening = "砂漠緑化"
industrial-revolution = "産業革命"
inter-species-war = "種族間戦争"
pandemic = "パンデミック"
step-toward-ecumenopolis = "エキュメノポリスへの第一歩"
magical-energy = "魔法みたいなエネルギー"
abundant-power = "みなぎるパワー"
exodus = "エクソダス"
giant-mirror = "巨大な鏡"
low-carbon-dioxide = "光合成できない"
destroy-planet = "もうこんな星いらない"
dark-clouds = "暗黒の曇り"

[achivement.desc]
grasslands = "草原が10タイル以上に広がる"
forests = "森林が50タイル以上に広がる"
animals = "惑星上に動物が存在する"
civilize = "動物を文明化する"
green-planet = "バイオマス量が2000Gtに達する"
melted-ice = "氷惑星の氷を全て溶かす"
desert-greening = "砂漠惑星でバイオマス量が600Gtに達する"
industrial-revolution = "産業化時代に文明が進化する"
inter-species-war = "異種族間での戦争が起きる"
pandemic = "1000以上の都市に疫病が伝染する"
step-toward-ecumenopolis = "地上の50%以上が都市で、人口が7500000以上"
magical-energy = "鉄器時代の文明にギフトエネルギーを供給する"
abundant-power = "30000TWの電力を得る"
exodus = "文明が宇宙へ旅立つ"
giant-mirror = "軌道ミラーを建設する"
low-carbon-dioxide = "大気中の二酸化炭素濃度が0.00003 atm以下になる"
destroy-planet = "バイオマス500Gt、人口1000以上の惑星を3000サイクル以内に不毛な星にする"
dark-clouds = "惑星の80%以上が雲に覆われる"
