[habitability]
ideal = "理想的"
adequate = "適切"
poor = "貧弱"
hostile = "過酷"

[planet]
custom = "カスタム"
continental = "大陸惑星"
archipelago = "多島海惑星"
ice = "氷惑星"
desert = "砂漠惑星"
barren = "不毛惑星"

[planet.desc]
continental = "海洋と大陸の両方が形成された惑星です。酸素こそ存在しないものの、海洋によって生命の維持は容易です。最もテラフォーミングに向いた天体です。"
archipelago = "惑星の大部分が海洋で、わずかな陸地が存在します。生命に適した環境ですが、陸上生命の生息域は限られるでしょう。"
ice = "氷に覆われた惑星です。その低い温度のため生命は存在しませんが、なんらかの方法で気温を上げれば、生命に欠かせない水を得ることができます。"
desert = "水がほとんど存在しない惑星で、その表面は乾燥した砂漠です。水を供給しなければ生命は存在し得ないでしょう。"
barren = "水も大気もほとんど存在しない惑星で、表面には岩石しかありません。生命に必要な物質はほとんど存在しません。"
